# Chatper 3. Deep Learning with PyTorch

* 싸이그래머 / 딥리워드 : Bandit [1]
* 김무성

---------------------

# Tensors

## Creation of tensors

In [2]:
import torch

In [3]:
import numpy as np

In [4]:
a = torch.FloatTensor(3, 2)

In [5]:
a

tensor([[0.0000, 0.0000],
        [0.0000, 0.0000],
        [0.0000, 0.0000]])

In [6]:
# initialize
a.zero_()

tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])

In [7]:
torch.FloatTensor([[1,2,3], 
                   [3,2,1]])

tensor([[1., 2., 3.],
        [3., 2., 1.]])

In [8]:
n = np.zeros(shape=(3,2))

In [10]:
n

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [9]:
b = torch.tensor(n)

In [11]:
b

tensor([[0., 0.],
        [0., 0.],
        [0., 0.]], dtype=torch.float64)

In [14]:
n = np.zeros(shape=(3,2),dtype=np.float32)
torch.tensor(n)

tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])

In [16]:
n = np.zeros(shape=(3,2))
torch.tensor(n, dtype=torch.float32)

tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])

## Scalar tensors

In [17]:
a = torch.tensor([1,2,3])

In [18]:
a

tensor([1, 2, 3])

In [19]:
s = a.sum()

In [20]:
s

tensor(6)

In [21]:
s.item()

6

-------------------------

-----------------------

# 참고자료

* [1] 주교재 : Deep Reinforcement Learning Hands-On - https://www.packtpub.com/big-data-and-business-intelligence/deep-reinforcement-learning-hands
* [2] 주교재 공식 깃헙 저장소 - https://github.com/PacktPublishing/Deep-Reinforcement-Learning-Hands-On