# Chatper 2. OpenAI Gym

---------------------

In [5]:
D_DISPLAY = True

In [ ]:
import gym

In [ ]:
env = gym.make("Taxi-v2")

In [ ]:
observation = env.reset()
for _ in range(1000):
    if D_DISPLAY :
        env.render()
    action = env.action_space.sample() # your agent here (this takes random actions)
    observation, reward, done, info = env.step(action)
env.close()

-------------------------

## 01_agent_anatomy.py

In [4]:
import random


class Environment:
    def __init__(self):
        self.steps_left = 10

    def get_observation(self):
        return [0.0, 0.0, 0.0]

    def get_actions(self):
        return [0, 1]

    def is_done(self):
        return self.steps_left == 0

    def action(self, action):
        if self.is_done():
            raise Exception("Game is over")
        self.steps_left -= 1
        return random.random()


class Agent:
    def __init__(self):
        self.total_reward = 0.0

    def step(self, env):
        current_obs = env.get_observation()
        actions = env.get_actions()
        reward = env.action(random.choice(actions))
        self.total_reward += reward


if __name__ == "__main__":
    env = Environment()
    agent = Agent()

    while not env.is_done():
        agent.step(env)

    print("Total reward got: %.4f" % agent.total_reward)


Total reward got: 4.8757


------------------------

## 02_cartpole_random.py

In [ ]:
import gym

if __name__ == "__main__":
    env = gym.make("CartPole-v0")

    total_reward = 0.0
    total_steps = 0
    obs = env.reset()

    while True:
        if D_DISPLAY :
            env.render()
        action = env.action_space.sample()
        obs, reward, done, _ = env.step(action)
        total_reward += reward
        total_steps += 1
        if done:
            break

    print("Episode done in %d steps, total reward %.2f" % (total_steps, total_reward))

env.close()

--------------------

In [ ]:
03_random_actionwrapper.py

In [1]:
import gym

In [2]:
env = gym.make('CartPole-v0')

WARN: gym.spaces.Box autodetected dtype as <class 'numpy.float32'>. Please provide explicit dtype.


In [3]:
for i_episode in range(20):
    observation = env.reset()
    for t in range(100):
        if D_DISPLAY :
            env.render()
        print(observation)
        action = env.action_space.sample()
        observation, reward, done, info = env.step(action)
        if done:
            print("Episode finished after {} timesteps".format(t+1))
            break
            
env.close()

[ 0.04876267 -0.01310186 -0.00881858  0.0021737 ]
[ 0.04850064 -0.20809624 -0.00877511  0.29206126]
[ 0.04433871 -0.01285028 -0.00293388 -0.00337625]
[ 0.04408171  0.18231363 -0.00300141 -0.29698341]
[ 0.04772798 -0.01276541 -0.00894108 -0.00524859]
[ 0.04747267  0.18248362 -0.00904605 -0.30073907]
[ 0.05112234  0.37773333 -0.01506083 -0.59626115]
[ 0.05867701  0.57306278 -0.02698605 -0.89364981]
[ 0.07013826  0.76854012 -0.04485905 -1.19469201]
[ 0.08550907  0.96421332 -0.06875289 -1.50109067]
[ 0.10479333  1.16009952 -0.0987747  -1.81442321]
[ 0.12799532  1.35617259 -0.13506317 -2.13609182]
[ 0.15511878  1.16262154 -0.177785   -1.88799724]
Episode finished after 13 timesteps
[ 0.00279351  0.00606723  0.02925401 -0.02245325]
[ 0.00291486  0.20075771  0.02880494 -0.30576455]
[ 0.00693001  0.00523737  0.02268965 -0.00413823]
[ 0.00703476 -0.19020251  0.02260689  0.29561632]
[ 0.00323071 -0.38563933  0.02851921  0.5953425 ]
[-0.00448208 -0.58114858  0.04042606  0.89687063]
[-0.01610505 -

[-0.03520505  0.20738544  0.00390752 -0.31577213]
[-0.03105734  0.01220804 -0.00240793 -0.02185947]
[-0.03081318 -0.18287929 -0.00284512  0.27006275]
[-0.03447077  0.01228314  0.00255614 -0.02351618]
[-0.0342251   0.20736834  0.00208582 -0.31539152]
[-0.03007774  0.01221674 -0.00422201 -0.02205153]
[-0.0298334  -0.18284441 -0.00466304  0.26929632]
[-0.03349029 -0.3778995   0.00072288  0.56050485]
[-0.04104828 -0.57303159  0.01193298  0.85341544]
[-0.05250891 -0.76831415  0.02900129  1.14982663]
[-0.0678752  -0.57358246  0.05199782  0.86637712]
[-0.07934685 -0.76937204  0.06932536  1.17494501]
[-0.09473429 -0.575216    0.09282426  0.90477585]
[-0.10623861 -0.77146416  0.11091978  1.22513194]
[-0.12166789 -0.9678257   0.13542242  1.5504078 ]
[-0.1410244  -1.16428752  0.16643057  1.88209504]
[-0.16431015 -0.97132357  0.20407248  1.64535359]
Episode finished after 20 timesteps
[ 0.0330569  -0.03589254 -0.00308686  0.02019915]
[ 0.03233905  0.15927355 -0.00268287 -0.27345612]
[ 0.03552452 -

-----------------------

## 04_cartpole_random_monitor.py

In [4]:
import gym

env = gym.make("CartPole-v0")

total_reward = 0.0
total_steps = 0
obs = env.reset()

while True:
    if D_DISPLAY :
        env.render()
    action = env.action_space.sample()
    obs, reward, done, _ = env.step(action)
    total_reward += reward
    total_steps += 1
    if done:
        break

print("Episode done in %d steps, total reward %.2f" % (total_steps, total_reward))
env.close()

WARN: gym.spaces.Box autodetected dtype as <class 'numpy.float32'>. Please provide explicit dtype.
Episode done in 20 steps, total reward 20.00


--------------------

In [1]:
import gym
env = gym.make("CartPole-v0")
env = gym.wrappers.Monitor(env, "recording")

total_reward = 0.0
total_steps = 0
obs = env.reset()

while True:
    action = env.action_space.sample()
    obs, reward, done, _ = env.step(action)
    total_reward += reward
    total_steps += 1
    if done:
        break

print("Episode done in %d steps, total reward %.2f" % (total_steps, total_reward))
env.close()
env.env.close()

WARN: gym.spaces.Box autodetected dtype as <class 'numpy.float32'>. Please provide explicit dtype.
Episode done in 12 steps, total reward 12.00


In [2]:
!ls

00_ch02.ipynb	       03_random_actionwrapper.py     test.py
01_agent_anatomy.py    04_cartpole_random_monitor.py
02_cartpole_random.py  recording


In [3]:
!ls recording/

openaigym.episode_batch.0.1333.stats.json
openaigym.manifest.0.1333.manifest.json
openaigym.video.0.1333.video000000.meta.json
openaigym.video.0.1333.video000000.mp4


-----------------------

# 참고자료

* [1] 주교재 : Deep Reinforcement Learning Hands-On - https://www.packtpub.com/big-data-and-business-intelligence/deep-reinforcement-learning-hands
* [2] 주교재 공식 깃헙 저장소 - https://github.com/PacktPublishing/Deep-Reinforcement-Learning-Hands-On
* [3] OpenAI Gym 공식 페이지 - https://gym.openai.com/